PROFILE_TMUX_OVERLAY="tmux-remote-minisforoum"
PROFILE_SSH_OVERLAY="minisforoum"
PROFILE_TOOL_SET="developer"
PROFILE_UI_THEME="orange-gas-plasma"
PROFILE_EXTRA_STOW_PACKAGES=(apps 1Password wezterm)
