PROFILE_TMUX_OVERLAY="tmux-remote-servalws"
PROFILE_SSH_OVERLAY="servalws"
PROFILE_UI_THEME="orange-gas-plasma"
PROFILE_ALLOWED_OS=(fedora)
PROFILE_TOOL_SET="desktop-full"
PROFILE_EXTRA_STOW_PACKAGES=(
    apps 1Password wezterm
    awesome awesome_wm_scripts picom dunst rofi polybar awesomewm-bin
)
PROFILE_MODULES=(
    system:xorg-libinput
    system:1password-unlock-polkit
    system:ly-display-manager
    system:ly-screen
    system:mate-polkit-package
    user:gnome-keyring-units
    user:awesome-auth-startup
)
