PROFILE_TMUX_OVERLAY="tmux-remote-zotac-box"
PROFILE_SSH_OVERLAY="zotac-box/${PROFILE_USER}_zotac-box"
PROFILE_TOOL_SET="minimal"
PROFILE_UI_THEME="orange-gas-plasma"

if [[ "$PROFILE_USER" == tima ]]; then
    PROFILE_EXTRA_STOW_PACKAGES=(apps)
fi
