-- Generated by theme-apply
local colors = {
    bg = "#1f1f28",
    fg = "#dcd7ba",
    accent = "#7e9cd8",
    cursor = "#c8c093",
    color0 = "#090618",
    color1 = "#c34043",
    color2 = "#76946a",
    color3 = "#c0a36e",
    color4 = "#7e9cd8",
    color5 = "#957fb8",
    color6 = "#6a9589",
    color7 = "#c8c093",
    color8 = "#727169",
}
return colors
