-- Generated by theme-apply
local colors = {
    bg = "#2d353b",
    fg = "#d3c6aa",
    accent = "#7fbbb3",
    cursor = "#d3c6aa",
    color0 = "#475258",
    color1 = "#e67e80",
    color2 = "#a7c080",
    color3 = "#dbbc7f",
    color4 = "#7fbbb3",
    color5 = "#d699b6",
    color6 = "#83c092",
    color7 = "#d3c6aa",
    color8 = "#475258",
}
return colors
